### ISSUE TITLE
Problems running test.py

### ISSUE THREAD

**Issue by Peregalli** [preethamam/CrackDenseLinkNet-DeepLearning-CrackSegmentation#1]
Hi! 

First of all, I want to congratulate you on your work, I found the article very interesting!

On the other hand, I would like to run the `DenseCrackLinkNet` model with my data, but before that, I was trying to run the `test.py` code with `Liu+Xincong+CrackSegNet+CDLN` data.  I followed the steps in the README to install the environment.

 My first issue occurred when downloading the weights of the DenseNet model, as I faced the following error:

`<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129)> ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1129) `

To resolve it, I manually downloaded from the link: http://data.lip6.fr/cadene/pretrainedmodels/densenet169-f470b90a4.pth and copy the file to the folder `/home/my_user/.cache/torch/hub/checkpoints/densenet169-f470b90a4.pth`. I also download the checkpoint (best_model_iou.pth) from [here](https://onedrive.live.com/?authkey=%21AJGOPqFoGv7dbhc&id=49B23BC11EECD6A8%2125686&cid=49B23BC11EECD6A8) and change `PATH` to load the weights. 

Assuming that this step is correct, now I'm facing the following error:

```
python test.py --data_dir Data/Liu+Xincong+CrackSegNet+CDLN/Testing/
Namespace(model='Linknet', backbone='densenet169', device_num=0, data_dir='Data/Liu+Xincong+CrackSegNet+CDLN/Testing/')
Traceback (most recent call last):
  File "/home/agustina/Documents/IMM_BID/CrackDenseLinkNet-DeepLearning-CrackSegmentation/CrackDenseLinkNet/test.py", line 166, in <module>
    best_model.load_state_dict(checkpoint["model_state_dict"])
  File "/home/agustina/anaconda3/envs/crackdenselinknet/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Linknet:
	Missing key(s) in state_dict: "encoder.features.conv0.weight", "encoder.features.norm0.weight", "encoder.features.norm0.bias", "encoder.features.norm0.running_mean", "encoder.features.norm0.running_var", "encoder.features.denseblock1.denselayer1.norm1.weight", "encoder.features.denseblock1.denselayer1.norm1.bias", "encoder.features.denseblock1.denselayer1.norm1.running_mean", "encoder.features.denseblock1.denselayer1.norm1.running_var", "encoder.features.denseblock1.denselayer1.conv1.weight", "encoder.features.denseblock1.denselayer1.norm2.weight", "encoder.features.denseblock1.denselayer1.norm2.bias", "encoder.features.denseblock1.denselayer1.norm2.running_mean", "encoder.features.denseblock1.denselayer1.norm2.running_var", "encoder.features.denseblock1.denselayer1.conv2.weight", "encoder.features.denseblock1.denselayer2.norm1.weight", "encoder.features.denseblock1.denselayer2.norm1.bias", "encoder.features.denseblock1.denselayer2.norm1.running_mean", "encoder.features.denseblock1.denselayer2.norm1.running_var", "encoder.features.denseblock1.denselayer2.conv1.weight", ....

And many other lines with the architecture
....

```

I'm not sure if I'm making an error when calling the model. I would appreciate it if you could lend me a hand to run the code. 

Sending regards! 

Agustina

**Comment by preethamam** [comment]
@Peregalli, were you able to download or load the `LinkNet` model?

**Comment by Peregalli** [comment]
If you're referring to downloading the weights of the best model (best_model_iou.pth file) linked in the README table, then yes, I've already downloaded them. The issue arises when I try to load those weights using` load_state_dict()` method at line 166.

**Comment by preethamam** [comment]
What I meant was, similar to the `DenseNet` encoder (backbone), you need `LinkNet` decoder. Were you able to download it? It is called in lines 74-78.

**Comment by Peregalli** [comment]
Okay, thank you for clarifying. So, no, I haven't downloaded that model. However, I went through those lines and didn't encounter any errors, which is strange. Could you please provide me with a link to download it? Should I also place that file in `/home/my_user/.cache/torch/hub/checkpoints/` like I did with the previous model?

**Comment by preethamam** [comment]
I have noticed depending on the weights downloaded, data parallelism `nn.DataParallel` sometimes messes up. Could you please uncomment the line  163 `best_model = nn.DataParallel(best_model, device_ids=[0])` and run the program? Please provide me with the output if there are any errors.

**Comment by Peregalli** [comment]
Well, good news. I managed to make predictions correctly, I just had to uncomment line 221. Thank you very much for your help! Although, I am not sure how I correctly loaded the weights if I didn't have the LinkNet model downloaded. 


In case anyone needs it: I also had issues with the torch version. `torch.cuda.is_available()` return was False, so I reinstalled it as shown in the link [here](https://stackoverflow.com/questions/66116155/how-to-tell-pytorch-which-cuda-version-to-take).

**Comment by preethamam** [comment]
Glad things worked well!

**Comment by preethamam** [comment]
Glad things worked well! I will close this issue then.

**Comment by preethamam** [comment]
@Peregalli, you should be good with `LinkNet` weights being downloaded. I remember that `DenseNet` was the culprit, while automatically downloaded via `smp` library. It hasn't had a problem with the `LinkNet`, though.

Just to clarify you commented `line 220` and uncommented `line 221`, right?
